[package]
name = "raytracer"
version = "0.1.0"
authors = ["Lynix <lynix680@gmail.com>", "yamashi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.13"
png = "0.15.0"
rand = "0.3"
rayon = "1.2"